version: '2'
services:
  db:
    image: "postgres:12.2"
    restart: always
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - /root/data/rubyfunctions/db_12_2:/var/lib/postgresql/data
  web:
    build: src/
    depends_on:
      - db
    links:
      - db
    volumes:
      - /root/data/rubyfunctions/uploads:/app/public/system
    restart: always
    ports:
      - '127.0.0.1:9000:3000'
    env_file:
      - .env
